## Repaso Regresión: Predicción de precios Inmobiliaria India

A continuación, se presenta un ejercicio en el que nos ponemos en el papel de un analista inmobiliario indio, donde tendremos que predecir el precio de las viviendas en base a sus características.

Dispones de 2 ficheros: ``train.csv``, de donde tendrás que extraer las características de las viviendas para entrenar tu modelo; y ``test.csv``, en el que tendrás los datos para la predicción (también tienen el target para poder hacer los cálculos del score).

La idea de este ejercicio es que realices diferentes transformaciones de variables y pruebes todos los algoritmos de regresión que conozcas para tratar de conseguir la mejor puntuación posible.

In [30]:
df = pd.read_csv("data/regression/train.csv")
df

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
0,Owner,0,0,2,BHK,1300.236407,1,1,"Ksfc Layout,Bangalore",12.969910,77.597960,55.0
1,Dealer,0,0,2,BHK,1275.000000,1,1,"Vishweshwara Nagar,Mysore",12.274538,76.644605,51.0
2,Owner,0,0,2,BHK,933.159722,1,1,"Jigani,Bangalore",12.778033,77.632191,43.0
3,Owner,0,1,2,BHK,929.921143,1,1,"Sector-1 Vaishali,Ghaziabad",28.642300,77.344500,62.5
4,Dealer,1,0,2,BHK,999.009247,0,1,"New Town,Kolkata",22.592200,88.484911,60.5
...,...,...,...,...,...,...,...,...,...,...,...,...
29446,Owner,0,0,3,BHK,2500.000000,1,1,"Shamshabad Road,Agra",27.140626,78.043277,45.0
29447,Owner,0,0,2,BHK,769.230769,1,1,"E3-108, Lake View Recidency,,Vapi",39.945409,-86.150721,16.0
29448,Dealer,0,0,2,BHK,1022.641509,1,1,"Ajmer Road,Jaipur",26.928785,75.828002,27.1
29449,Owner,0,0,2,BHK,927.079009,1,1,"Sholinganallur,Chennai",12.900150,80.227910,67.0
29450,Dealer,0,1,2,BHK,896.774194,1,1,"Jagatpura,Jaipur",26.832353,75.841749,27.8

In [31]:
df = pd.read_csv("data/regression/test.csv")
df

,Unnamed: 0,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
0,22703,Owner,0,1,3,BHK,1562.212829,1,1,"Hosa Road,Bangalore",12.863589,77.656426,85.0
1,11107,Dealer,0,0,2,BHK,1075.017527,1,1,"Sector-35G Kharghar,Mumbai",19.038205,73.066120,92.0
2,14235,Owner,0,0,3,BHK,1320.035201,1,1,"Peer Muchalla,Panchkula",30.660437,76.861517,45.0
3,10613,Dealer,0,0,1,BHK,660.066007,1,1,"Dombivli (East),Maharashtra",19.216700,73.083300,46.0
4,5455,Dealer,0,0,2,BHK,1293.267402,1,1,"Alwar Bhiwadi Road,Bhiwadi",28.210000,76.870000,34.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8695,16534,Dealer,0,0,2,BHK,909.176206,1,1,"Manpada,Mumbai",19.239813,72.962722,96.9
8696,11022,Dealer,1,0,2,BHK,1309.243257,0,1,"Devarabisanahalli,Bangalore",12.969910,77.597960,100.0
8697,8028,Dealer,0,1,4,BHK,1679.865611,1,1,"Yeshwanthpur,Bangalore",12.969910,77.597960,140.0
8698,13587,Owner,0,0,2,BHK,1250.000000,1,1,"Krishna Nagar,Lucknow",28.656401,77.288914,65.0
8699,29386,Dealer,0,1,3,BHK,1727.115717,1,1,"Rajaji Nagar,Bangalore",12.984700,77.549100,140.0